-- MySQL Script generated by MySQL Workbench
-- 02/23/16 12:53:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`mata_kuliah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mata_kuliah` (
  `id_mk` VARCHAR(10) NOT NULL,
  `nama_mk` VARCHAR(50) NULL,
  PRIMARY KEY (`id_mk`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mahasiswa` (
  `nim` VARCHAR(20) NOT NULL,
  `nama_mhs` VARCHAR(50) NULL,
  PRIMARY KEY (`nim`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`penutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`penutor` (
  `nim_penutor` VARCHAR(20) NOT NULL,
  `nama_penutor` VARCHAR(50) NULL,
  PRIMARY KEY (`nim_penutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mahasiswa_has_mata_kuliah`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mahasiswa_has_mata_kuliah` (
  `mahasiswa_nim` VARCHAR(20) NOT NULL,
  `mata_kuliah_id_mk` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`mahasiswa_nim`, `mata_kuliah_id_mk`),
  INDEX `fk_mahasiswa_has_mata_kuliah_mata_kuliah1_idx` (`mata_kuliah_id_mk` ASC),
  INDEX `fk_mahasiswa_has_mata_kuliah_mahasiswa_idx` (`mahasiswa_nim` ASC),
  CONSTRAINT `fk_mahasiswa_has_mata_kuliah_mahasiswa`
    FOREIGN KEY (`mahasiswa_nim`)
    REFERENCES `mydb`.`mahasiswa` (`nim`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mahasiswa_has_mata_kuliah_mata_kuliah1`
    FOREIGN KEY (`mata_kuliah_id_mk`)
    REFERENCES `mydb`.`mata_kuliah` (`id_mk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`absen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`absen` (
  `tgl` TIMESTAMP(4) NOT NULL,
  `absen` TINYINT(1) NULL,
  `mahasiswa_has_mata_kuliah_mahasiswa_nim` VARCHAR(20) NOT NULL,
  `mahasiswa_has_mata_kuliah_mata_kuliah_id_mk` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`tgl`, `mahasiswa_has_mata_kuliah_mahasiswa_nim`, `mahasiswa_has_mata_kuliah_mata_kuliah_id_mk`),
  INDEX `fk_absen_mahasiswa_has_mata_kuliah1_idx` (`mahasiswa_has_mata_kuliah_mahasiswa_nim` ASC, `mahasiswa_has_mata_kuliah_mata_kuliah_id_mk` ASC),
  CONSTRAINT `fk_absen_mahasiswa_has_mata_kuliah1`
    FOREIGN KEY (`mahasiswa_has_mata_kuliah_mahasiswa_nim` , `mahasiswa_has_mata_kuliah_mata_kuliah_id_mk`)
    REFERENCES `mydb`.`mahasiswa_has_mata_kuliah` (`mahasiswa_nim` , `mata_kuliah_id_mk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`mata_kuliah_has_penutor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`mata_kuliah_has_penutor` (
  `mata_kuliah_id_mk` VARCHAR(10) NOT NULL,
  `penutor_nim_penutor` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`mata_kuliah_id_mk`, `penutor_nim_penutor`),
  INDEX `fk_mata_kuliah_has_penutor_penutor1_idx` (`penutor_nim_penutor` ASC),
  INDEX `fk_mata_kuliah_has_penutor_mata_kuliah1_idx` (`mata_kuliah_id_mk` ASC),
  CONSTRAINT `fk_mata_kuliah_has_penutor_mata_kuliah1`
    FOREIGN KEY (`mata_kuliah_id_mk`)
    REFERENCES `mydb`.`mata_kuliah` (`id_mk`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mata_kuliah_has_penutor_penutor1`
    FOREIGN KEY (`penutor_nim_penutor`)
    REFERENCES `mydb`.`penutor` (`nim_penutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
